# Generated by Django 6.1 on 2026-10-05 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=32, unique=True)),
                ('department_name', models.CharField(max_length=128)),
                ('hod_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('roll_no', models.CharField(blank=True, max_length=64)),
                ('class_name', models.CharField(blank=True, max_length=64)),
                ('year', models.CharField(blank=True, max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('dept_admin', 'Department Admin'), ('superadmin', 'Super Admin')], default='student', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('profile_photo', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
                ('portfolio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
        ),
    ]
