# Generated by Django 6.1 on 2026-10-05 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('complaint', 'Complaint'), ('leave', 'Leave Request'), ('certificate', 'Certificate Request'), ('technical', 'Technical Issue'), ('academic', 'Academic Request'), ('general', 'General Request')], max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.user')),
            ],
        ),
    ]
